package com.hvac.workflow.model;

import jakarta.validation.constraints.NotBlank;

import java.util.Map;

// Request DTO received from frontend create/update technician forms.
public record TechnicianRequest(
        @NotBlank String employeeNo,
        String title,
        @NotBlank String fullName,
        @NotBlank String firstName,
        String middleName,
        @NotBlank String lastName,
        String gender,
        String dateOfBirth,
        Integer age,
        String maritalStatus,
        String jobTitle,
        String category,
        String payrollStatus,
        Double amount,
        String grading,
        String jobGroup,
        String location,
        String employmentDate,
        String entryChecklist,
        String status,
        String exitDate,
        String lengthService,
        String exitChecklist,
        Integer annualLeaveEntitlement,
        Integer leaveTaken,
        Integer leaveBalance,
        String socialSecurityNo,
        String bankName,
        String bankBranchName,
        String accountNo,
        String taxIdentificationNo,
        String ghanaCardNumber,
        Boolean providentFund,
        String vehicleAndFuel,
        Double transportAllowanceGallons,
        Boolean cellPhone,
        Double airtimeAmount,
        Boolean lunch,
        String medicalPlan,
        String spouseOrNa,
        Integer childrenCount,
        String mobilePhoneNo,
        String businessPhoneNo,
        String homePhoneNo,
        String emailAddress,
        String postalAddress,
        String residentialAddress,
        String emergencyContact,
        String emergencyPhoneNo,
        String relationship,
        String spouseName,
        String namesOfChildren,
        Integer numberOfDependents,
        String nextOfKinName,
        String nextOfKinContactDetails,
        String guarantorName,
        String guarantorContact,
        String guarantorResidentialAddress,
        String guarantorGhanaCard,
        Map<String, String> customFields
) {
}
